export interface IGoods {
    title: string;
    image: string;
    price: string;
    text: string;
    id: string;
    weight: string;
    calory: string;
    protein: string;
    fat: string;
    carb: string;
};

// export type IData = Array<IGoods>;

[
    {
     "title": "Деревенская с бужениной",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/200ef6ddfb814852ad1a2456c5d7c62c_292x292.webp",
     "price": "500",
     "text": "Запеченная буженина из свинины, моцарелла, картофель из печи, маринованные огурчики, красный лук, чеснок, фирменный томатный соус, соус ранч",
     "type": "Pizza",
     "id": "1",
     "weight": "710",
     "calory": "221.6",
     "protein": "5.9",
     "fat": "8.3",
     "carb": "29.3"
    },
    {
     "title": "Двойной Воппер с сыром",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/22663dcdc3924b210e66b944955b32fc.webp",
     "price": "300",
     "text": "Два аппетитных, приготовленных на огне бифштекса из 100% говядины, два нежных ломтика сыра, сочные помидоры, свежий нарезанный листовой салат, густой майонез, хрустящие маринованные огурчики и свежий лук на нежной булочке с кунжутом.",
     "type": "Burger",
     "id": "2",
     "weight": "368",
     "calory": "240",
     "protein": "10",
     "fat": "16",
     "carb": "14"
    },
    {
     "title": "АНГУС Шеф",
     "image": "https://orderapp-static.burgerkingrus.ru/x512/mobile_image/a9b0d5d5db8698831811a566c6dd41e1.webp",
     "price": "400",
     "text": "Невероятно нежный 150-граммовый мраморный бифштекс на французской булочке бриошь под соусом барбекю и натуральные ингредиенты со всего мира: салат Романо, сыр Гауда, бекон, лук фри и свежие овощи. Стопроцентная мраморная вкуснятина — пробуй срочно!",
     "type": "Burger",
     "id": "3",
     "weight": "338",
     "calory": "280",
     "protein": "11",
     "fat": "18",
     "carb": "19"
    },
    {
     "title": "Эби манго",
     "image": "https://kcdn.tanuki.ru//images/1/tYZDTqj5MalhfQ64YaM2LZYm5FiAW_V6.jpg?width=400&height=400",
     "price": "370",
     "text": "креветка, краб-микс, манго, сыр, тобико, кинза, соус «Спайси-манго», рис, нори, 6 шт.",
     "type": "Roll",
     "id": "4",
     "weight": "165",
     "calory": "303",
     "protein": "11",
     "fat": "8",
     "carb": "48"
    },
    {
     "title": "Ветчина и сыр",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/cea570842b754c52b786c231c65bd2e2_292x292.webp",
     "price": "369",
     "text": "Ветчина, моцарелла, фирменный соус альфредо",
     "type": "Pizza",
     "id": "5",
     "weight": "500",
     "calory": "274",
     "protein": "10.3",
     "fat": "9.7",
     "carb": "34.6"
    },
    {
     "title": "Сырная",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/d9c609f1422247f2b87b6293eb461ff0_292x292.webp",
     "price": "289",
     "text": "Моцарелла, сыры чеддер и пармезан, фирменный соус альфредо",
     "type": "Pizza",
     "id": "6",
     "weight": "490",
     "calory": "284.1",
     "protein": "10.4",
     "fat": "10.4",
     "carb": "35.3"
    },
    {
     "title": "Ичиро",
     "image": "https://kcdn.tanuki.ru//images/1/fkv0FK9caIHhEUXxJYDKEa0tZ8cGRU2W.jpg?width=400&height=400",
     "price": "450",
     "text": "Креветка, угорь, авокадо, сыр чеддер, тобико, зеленый лук, соус «Спайси-манго», рис, нори, 6 шт.",
     "type": "Roll",
     "id": "7",
     "weight": "200",
     "calory": "500",
     "protein": "23",
     "fat": "25",
     "carb": "47"
    },
    {
     "title": "Одзу",
     "image": "https://kcdn.tanuki.ru//images/1/G9gS4P7q1GTMAqg86kh2mJ4z_aO5G1tR.jpg?width=400&height=400",
     "price": "450",
     "text": "Лосось, тунец, авокадо, тобико, салат, зеленый лук, соусы «Нисуаз», спайс и унаги, рис, нори, 8 шт.",
     "type": "Roll",
     "id": "8",
     "weight": "200",
     "calory": "422",
     "protein": "19",
     "fat": "17",
     "carb": "49"
    },
    {
     "title": "Сырбургер",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/b8889df19a29feeb760859a18225ea42.webp",
     "price": "631",
     "text": "Настоящий Сырбургер – это 100% говядина на огне, маринованный огурчик, подрумяненная булочка с кунжутом, свежий хрустящий салат, и конечно же – сырный-сырный соус Чеддер. В самое СЫРдечко!",
     "type": "Burger",
     "id": "9",
     "weight": "113",
     "calory": "280",
     "protein": "12",
     "fat": "14",
     "carb": "27"
    },
    {
     "title": "Пепперони фреш",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/27c9bbd0af3a4d1d84a086d9c2f1656d_292x292.webp",
     "price": "289",
     "text": "Пикантная пепперони, увеличенная порция моцареллы, томаты, фирменный томатный соус",
     "type": "Pizza",
     "id": "10",
     "weight": "610",
     "calory": "249.3",
     "protein": "10.1",
     "fat": "9.5",
     "carb": "29.1"
    },
    {
     "title": "Чоризо фреш",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/02ca2561953b488993878d1f70e359de_292x292.webp",
     "price": "340",
     "text": "Фирменный томатный соус, моцарелла, острая чоризо, сладкий перец",
     "type": "Pizza",
     "id": "11",
     "weight": "490",
     "calory": "267.9",
     "protein": "10.1",
     "fat": "8.4",
     "carb": "36.3"
    },
    {
     "title": "Беконайзер",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/9a2f9c7f0b8514edc7666d025b07157b.webp",
     "price": "410",
     "text": "Встречай самый внушительный бургер в коллекции Бургер Кинг. Много мяса, много бекона и много сыра - все, как ты любишь, и ничего лишнего!",
     "type": "Burger",
     "id": "12",
     "weight": "328",
     "calory": "310",
     "protein": "14",
     "fat": "21",
     "carb": "15"
    },
    {
     "title": "Калифорния лайт",
     "image": "https://kcdn.tanuki.ru//images/1/IOkgQAji6v7LOAQlPTuT7OjALakzNmXE.jpg?width=400&height=400",
     "price": "430",
     "text": "краб-микс, авокадо, огурец, тобико, кунжут, рис, нори, 6 шт.",
     "type": "Roll",
     "id": "13",
     "weight": "160",
     "calory": "335",
     "protein": "9",
     "fat": "13",
     "carb": "45"
    },
    {
     "title": "Калифорния хот",
     "image": "https://kcdn.tanuki.ru//images/1/6pD6VITbiTOOKlEM8W7eUapaJL7s5A3g.jpg?width=400&height=400",
     "price": "510",
     "text": "краб-микс, авокадо, огурец, тобико, кунжут, рис, нори, 6 шт.",
     "type": "Roll",
     "id": "14",
     "weight": "190",
     "calory": "506",
     "protein": "11",
     "fat": "31",
     "carb": "47"
    },
    {
     "title": "Сырный цыпленок",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/42360a7dcb7640c998b723231586fe84_292x292.webp",
     "price": "469",
     "text": "Цыпленок, моцарелла, сыры чеддер и пармезан, сырный соус, томаты, фирменный соус альфредо, чеснок",
     "type": "Pizza",
     "id": "15",
     "weight": "610",
     "calory": "246.1",
     "protein": "11.2",
     "fat": "8.9",
     "carb": "28.7"
    },
    {
     "title": "Чизбургер",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/aabf8e02d69d4d979574f3b7941024f6.webp",
     "price": "110",
     "text": "булочка для гамбургера с кунжутом(55 гр), котлета из говядины HAMBURGER, огурцы маринованные, кетчуп томатный, горчица, сыр плавленый",
     "type": "Burger",
     "id": "16",
     "weight": "118",
     "calory": "250",
     "protein": "11",
     "fat": "9.5",
     "carb": "28"
    },
    {
     "title": "Калифорния с лососем лайт",
     "image": "https://kcdn.tanuki.ru//images/1/nqpBtGGPnbsXqcSmWdeq77CpM9G71cl6.jpg?width=400&height=400",
     "price": "440",
     "text": "лосось, авокадо, огурец, тобико, кунжут, рис, нори, 6 шт.",
     "type": "Roll",
     "id": "17",
     "weight": "155",
     "calory": "398",
     "protein": "14",
     "fat": "19",
     "carb": "43"
    },
    {
     "title": "Гамбургер",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/141ccfd46f9b40b4d3d2fb3b4702c1ab.webp",
     "price": "100",
     "text": "булочка для гамбургера с кунжутом(55 гр), котлета из говядины HAMBURGER, огурцы маринованные, кетчуп томатный, горчица",
     "type": "Burger",
     "id": "18",
     "weight": "108",
     "calory": "230",
     "protein": "9.5",
     "fat": "7.5",
     "carb": "30"
    },
    {
     "title": "Мясная",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/18dbb12240b041a191c9dc73c9c1f4ef_292x292.webp",
     "price": "469",
     "text": "Цыпленок, ветчина, пикантная пепперони, острая чоризо, моцарелла, фирменный томатный соус",
     "type": "Pizza",
     "id": "19",
     "weight": "600",
     "calory": "253.5",
     "protein": "11.1",
     "fat": "9.5",
     "carb": "29.2"
    },
    {
     "title": "Воппер Джуниор",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/455600d3c6df374a21bc65a56267405c.webp",
     "price": "120",
     "text": "булочка для гамбургера с кунжутом(55 гр), котлета из говядины WHOPPER, майонез для салата, салат Айсберг, томаты, огурцы маринованные, лук репчатый, кетчуп томатный",
     "type": "Burger",
     "id": "20",
     "weight": "143",
     "calory": "220",
     "protein": "7",
     "fat": "11",
     "carb": "22"
    },
    {
     "title": "Дракон лайт",
     "image": "https://kcdn.tanuki.ru//images/1/7AxiWEsuDZTPuR3NjwNgmqXHcfM3JNMd.jpg?width=400&height=400",
     "price": "435",
     "text": "угорь, авокадо, сыр, икра тобико, лук зеленый, стружка тунца, кунжут, рис, нори, 6 шт.",
     "type": "Roll",
     "id": "21",
     "weight": "150",
     "calory": "383",
     "protein": "14",
     "fat": "18",
     "carb": "42"
    },
    {
     "title": "Цыпленок ранч",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/e379c72af6c54f81b7b4e6ffbb2b1729_292x292.webp",
     "price": "460",
     "text": "Цыпленок, ветчина, соус ранч, моцарелла, томаты, чеснок",
     "type": "Pizza",
     "id": "22",
     "weight": "650",
     "calory": "250.6",
     "protein": "10",
     "fat": "10.8",
     "carb": "26.6"
    },
    {
     "title": "Окинава",
     "image": "https://kcdn.tanuki.ru//images/1/0LQX_kF6uy511H4p3R2jsoP4ITFSvAel.jpg?width=400&height=400",
     "price": "355",
     "text": "креветка темпура, огурец, сыр, тобико, кунжут, рис, нори, 4 шт.",
     "type": "Roll",
     "id": "23",
     "weight": "125",
     "calory": "246",
     "protein": "8",
     "fat": "5",
     "carb": "43"
    },
    {
     "title": "Гранд Чиз",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/f45108bd834c04892b6036d6e6caaf87.webp",
     "price": "199",
     "text": "Наша новая классика с нежным бифштексом по-домашнему: к фирменной говядине мы добавили немного сочной курочки. Любимое сочетание сыра Чеддер, маринованных огурчиков, лука, кетчупа и горчицы — на подрумяненной булочке с кунжутом.",
     "type": "Burger",
     "id": "24",
     "weight": "178",
     "calory": "260",
     "protein": "11",
     "fat": "16",
     "carb": "19"
    },
    {
     "title": "Цыпленок барбекю",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/45cc8ffb190c4a28aaf1863a67f675c7_292x292.webp",
     "price": "519",
     "text": "Цыпленок, бекон, соус барбекю, красный лук, моцарелла, фирменный томатный соус",
     "type": "Pizza",
     "id": "25",
     "weight": "680",
     "calory": "262.6",
     "protein": "9.8",
     "fat": "11.6",
     "carb": "27.9"
    },
    {
     "title": "Гранд Чиз Фреш",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/98522c1c619de4241d772123f8060914.webp",
     "price": "239",
     "text": "Особенная версия Гранд Чиза — со свежими овощами. Новый бифштекс по-домашнему (к фирменной говядине мы добавили немного сочной курочки), ломтики сыра Чеддер, хрустящий Айсберг, помидоры, лук, маринованные огурчики, кетчуп и горчица.",
     "type": "Burger",
     "id": "26",
     "weight": "205",
     "calory": "230",
     "protein": "10",
     "fat": "14",
     "carb": "17"
    },
    {
     "title": "Орандж краб",
     "image": "https://kcdn.tanuki.ru//images/1/eJxDwO_0C3AvmCvnczHIxcnU9QelMXfn.jpg?width=400&height=400",
     "price": "500",
     "text": "краб-микс, авокадо, сыр, микс соусов, хрустящая маменори, лук зеленый, 6 шт.",
     "type": "Roll",
     "id": "27",
     "weight": "150",
     "calory": "404",
     "protein": "10",
     "fat": "15",
     "carb": "57"
    },
    {
     "title": "Цыпленок карри",
     "image": "https://dodopizza-a.akamaihd.net/static/Img/Products/c8ac7d2eb95b4bd0b8bc2f366415896c_292x292.webp",
     "price": "420",
     "text": "Цыпленок, ананасы, соус карри, красный лук, сладкий перец, моцарелла, фирменный томатный соус",
     "type": "Pizza",
     "id": "28",
     "weight": "640",
     "calory": "211.8",
     "protein": "9.3",
     "fat": "6.4",
     "carb": "27.9"
    },
    {
     "title": "Ангус Камамбер",
     "image": "https://orderapp-static.burgerkingrus.ru/x256/mobile_image/19c87ecb138981c836975c7072fd988c.webp",
     "price": "399",
     "text": "Его Сырное Вкуснейшество! Мраморный бифштекс и тающий Камамбер в хрустящей корочке под соусом Бальзамик! А ещё свежие овощи, заправленные грибным соусом, — всё на булочке бриошь.",
     "type": "Burger",
     "id": "29",
     "weight": "360",
     "calory": "250",
     "protein": "11",
     "fat": "12",
     "carb": "25"
    },
    {
     "title": "Скин",
     "image": "https://kcdn.tanuki.ru//images/1/RcbhmKE1T7aR108FxGNYyzy6wY4CX6Km.jpg?width=400&height=400",
     "price": "305",
     "text": "жареная кожа лосося, стружка тунца, огурец, сыр, тобико, соус спайс, зеленый лук, рис, нори, 6 шт.",
     "type": "Roll",
     "id": "30",
     "weight": "160",
     "calory": "325",
     "protein": "8",
     "fat": "10",
     "carb": "51"
    }
   ]